export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_VEHICLE_BEGIN = "CREATE_VEHICLE_BEGIN";
export const CREATE_VEHICLE_SUCCESS = "CREATE_VEHICLE_SUCCESS";
export const CREATE_VEHICLE_ERROR = "CREATE_VEHICLE_ERROR";

export const GET_VEHICLES_BEGIN = "GET_VEHICLES_BEGIN";
export const GET_VEHICLES_SUCCESS = "GET_VEHICLES_SUCCESS";

export const SET_EDIT_VEHICLE = "SET_EDIT_VEHICLE";

export const DELETE_VEHICLE_BEGIN = "DELETE_VEHICLE_BEGIN";

export const EDIT_VEHICLE_BEGIN = "EDIT_VEHICLE_BEGIN";
export const EDIT_VEHICLE_SUCCESS = "EDIT_VEHICLE_SUCCESS";
export const EDIT_VEHICLE_ERROR = "EDIT_VEHICLE_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
